### ISSUE TITLE
Repositories updated ?

### ISSUE THREAD

**Issue by mrmarten** [WPI-Humanoid-Robotics-Lab/drcsim_docker#2]
Seems like a bunch of repo's have been updated so the Docker image is not working at the moment. Can you please update it?

This is my output:

> Sending build context to Docker daemon  159.7kB
Step 1/53 : FROM nvidia/cuda:8.0-runtime-ubuntu16.04
 ---> 8cc11a855b4d
Step 2/53 : LABEL maintainer "vvjagtap@wpi.edu"
 ---> Using cache
 ---> 721ee10c602f
Step 3/53 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 8d05ee9d77b5
Step 4/53 : RUN rm /bin/sh && ln -s /bin/bash /bin/sh
 ---> Using cache
 ---> 8d96a2bd3ea5
Step 5/53 : RUN cat /etc/resolv.conf
 ---> Using cache
 ---> 9cb78ed8a3cc
Step 6/53 : RUN apt-get -y update && apt-get install -y sudo apt-utils
 ---> Running in dd6fee91316c
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
  Could not resolve host: developer.download.nvidia.com
Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/InRelease  Could not resolve host: developer.download.nvidia.com
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package sudo
E: Package 'apt-utils' has no installation candidate
The command '/bin/bash -c apt-get -y update && apt-get install -y sudo apt-utils' returned a non-zero code: 100
running drcsim 0.11 docker container
IP address is 172.16.0.0 
ROS master URI : http://172.16.0.0:11311 
Gazebo master URI : http://172.16.0.0:11345
Unable to find image 'drcsim:0' locally
docker: Error response from daemon: pull access denied for drcsim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by AshayAswale** [comment]
Hi Marten, I could not replicate the issue you raised. I was able to build the docker in both ubuntu 16.04 and 18.04 with and without some system packages. 
But I tried to fix other possible issues. Let us know if you still have issues in building the docker

**Comment by AshayAswale** [comment]
Please reopen the issue if the problem persists.
